theme: null
markdown: kramdown
baseurl: ""  # Replace with your actual repository name
url: "https://AnnaKopatko.github.io"       # Replace with your GitHub username
collections:
  posts:
    output: true
    permalink: /:title