theme: null
markdown: kramdown
baseurl: "/COMPREHENSIVE-DEPLOYMENT-GUIDE"  # Replace with your actual repository name
url: "https://yourusername.github.io"       # Replace with your GitHub username
collections:
  posts:
    output: true
    permalink: /:title