theme: null
markdown: kramdown
collections:
  posts:
    output: true
permalink: /:title

defaults:
  - scope:
      path: ""
    values:
      head: |
        <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@300;400;600;700&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="/assets/css/style.css">
