title: Anna Kopatko
description: Deep Learning Engineer | Perception | Physics
baseurl: "" # keep it empty unless you are using a project page
url: "https://AnnaKopatko.github.io" # Your GitHub Pages URL

theme: minima # still use minima, but we override it with custom CSS

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Build settings
markdown: kramdown
highlighter: rouge

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

sass:
  style: compressed
